### ISSUE TITLE
[Docs] Questions about visible_instance_ids

### ISSUE THREAD

**Issue by linxuewu** [OpenRobotLab/EmbodiedScan#65]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

1. `visible_instance_ids` starts from 0, while `bbox_id` starts from 1? `visible_instance_ids` is the list index representing instance? 
2. When training multiview and grounding, only some images are sampled instead of all images. Why are `invisible_instance_ids` not used to filter invisible GT?

**Comment by Tai-Wang** [comment]
1. Sorry for the confusion caused. `visible_instance_ids` corresponds to the index of boxes in the gt list, while the bbox_id corresponds to the box id during the annotation process, which starts from 1.
2. We do not filter invisible GT because we would like to keep the setting more generalizable. Another thing that is interesting to explore is how to choose the input images according to the given prompt. The current setting just follows the simplest setting regarding the input and uses the fixed selected multi-view images.
