### ISSUE TITLE
[Docs] The meaning of axis_align_matrix

### ISSUE THREAD

**Issue by SiyuanWei** [OpenRobotLab/EmbodiedScan#89]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

Hi, I am confused about the axis_align_matix meaning. Does it come from the original source dataset setup (scannet, 3rscan,matterport3d) or "Is it used to convert the world coordinate system to a specific position, for example, aligning the z-axis with the direction opposite to gravity?

**Comment by Tai-Wang** [comment]
Yes, this is a legacy convention from previous works. Since the original 3D box annotations of ScanNet are axis-aligned (converted from point-wise segmentation gts), previous works for 3D detection typically convert the input point clouds to the axis-aligned coordinate system. The meaning of axis-aligned is that the horizontal axes are typically aligned with the walls, and the vertical axis is aligned with the direction of gravity. The origin is typically set on/near the floor.
